### ISSUE TITLE
FlutterContacts.getContacts( withProperties: true,) contacts are empty

### ISSUE THREAD

**Issue by XiaoJianXiaoXu** [QuisApp/flutter_contacts#10]
flutter_contacts: ^0.2.2
Flutter 1.22.4
iOS Simulator iPhone 12 Pro Max - 14.3

Use FlutterContacts.getContacts(). I can get contacts, but only hav display name, and id. I insert the contact with Phone and Organization, but phones and organizations is empty.
Then I use FlutterContacts.getContacts( withProperties: true,), contacts are empty.

**Comment by XiaoJianXiaoXu** [comment]
#4 don't have getFullContacts.

**Comment by joachimvalente** [comment]
Hi, `getFullContacts` no longer exists. Now instead you should use `getContacts(withProperties: true, withPhoto: true, withThumbnail: true)`.

If you fetch shallow contacts (e.g. without properties), you can add a phone number to it if you want, but you won't be able to call `contact.update()` (to prevent you from accidentally erasing existing properties).

**Comment by joachimvalente** [comment]
Closing – feel free to reopen if that didn't answer your question.

**Comment by Faisalkc4u** [comment]
(await FlutterContacts.getContacts(withProperties: true)).toList() is giving empty list

**Comment by joachim-quis** [comment]
Do you have any contacts? In particular any contacts *not* on the SIM card? It's a known issue that SIM card contacts are not yet supported. See #26

**Comment by joachim-quis** [comment]
Also, can you share your entire code?

**Comment by Faisalkc4u** [comment]
The same code was working before also I got the numbers in real-devices.
I could able to fetch the contacts before, But now the code is giving an empty list

``` 
try {
      if (!await hasPermission()) {
        await requestPermission();
      }
      if (!await hasPermission()) {
        return [];
      }
      mycontacts =
          (await FlutterContacts.getContacts(withProperties: true)).toList();

      contactFilterLogic();

    } catch (e) {

    }
```

**Comment by joachim-quis** [comment]
@Faisalkc4u can you confirm
(1) you have contacts on the device
(2) they are not SIM card contacts
(3) you gave permission (by going to Settings)

Also can you replace you code with this and try again?

```dart
if (!await hasPermission()) {
  print('No permission');
} else {
  final contacts = await FlutterContacts.getContacts();
  print('Found ${contacts.length} contacts');
}
```

and paste the output?

**Comment by Faisalkc4u** [comment]
I have already tried this way, but the results are same.
I would like add one point that, the same code was working fine. But suddenly it is not giving the same output before.

Sure i will update the code output

**Comment by joachim-quis** [comment]
In that case could you also try updating your `pubspec.yaml` with a specific `flutter_contacts` version (see [versions here](https://pub.dev/packages/flutter_contacts/versions)) and let us know in which version it stopped working?
