### ISSUE TITLE
Country iso code is added to the phone number while saving the contact using vcard.

### ISSUE THREAD

**Issue by kartikmalhotra** [QuisApp/flutter_contacts#105]
I am trying to save the contact to my contact list using  [vcard_maintained](https://pub.dev/packages/vcard_maintained) package on some devices it is working fine while on iPhone 12 and 13, It is not saving the number in the correct format. Please check the screenshots attached for more info<img width="527" alt="image" src="https://user-images.githubusercontent.com/37996511/230904876-0e9e65d8-b921-4d3f-acd1-06e9cd3b1074.png">
![IMG_1568](https://user-images.githubusercontent.com/37996511/230905528-c32791bb-d0aa-4c68-9b98-1518a1040146.png)

**Comment by sunil3590** [comment]
Trying to save `+164XXXXXXXX` but `US+164XXXXXXXX` gets saved in the phone book

**Comment by joachim-quis** [comment]
I suspect this is an error outside of `flutter_contacts`. This package just accepts any string as a phone, so the error is probably upstream. Please re-open if you disagree, and add some `print(vCard.cellPhone)` and other debug info so it's easier to debug.
