### ISSUE TITLE
Incorrect Date Format

### ISSUE THREAD

**Issue by dallinwelch** [QuisApp/flutter_contacts#107]
I found this only by trying Android so far but, if you have a contact with a birthdate assigned in the contact and the date format is not MM/DD/YY then you will get an error. Andriod allows you to not include the year and it broke my code. I found out which contact it was and they had the birthday month of 03/21 but the code requires a year. Please be aware as I can fix this on my end but all my users now need to update any birthdays they have saved to their contacts.

**Comment by joachim-quis** [comment]
Thanks @dallinwelch - could you re-open this with more details, like a code snippet? The API of `flutter_contacts` allows a nullable year in theory, so I'd be curious to hear why it's not working for you.
