### ISSUE TITLE
App crash issue while updating an existing contact

### ISSUE THREAD

**Issue by hssn-hassnain** [QuisApp/flutter_contacts#108]
E:Too many content provider operations between yield points. The maximum number of operations per yield point is 500
I have found out the issue is at FlutterContacts.kt file line 556. This happen when 1 contact have multiple numbers

**Comment by joachim-quis** [comment]
Thanks @hssn-hassnain - closing as duplicate of https://github.com/QuisApp/flutter_contacts/issues/140
