### ISSUE TITLE
How to get UpdatedAt timestamp for a contact?

### ISSUE THREAD

**Issue by agent515** [QuisApp/flutter_contacts#118]
Hello. I'm trying to sync contacts with local storage and remote database. And I'm thinking `updatedAt` field would be the best to determine if there are any latest changes that should be synced. But I could not find such field in the [Contact](https://github.com/QuisApp/flutter_contacts/blob/993498ae5a3b0888551475932d453123efc396af/lib/contact.dart#LL68C7-L68C14).

On Android, I found `ContactsContract.Contacts.CONTACT_LAST_UPDATED_TIMESTAMP` to do something similar. But there are also some issues with this field highlighted [here](https://stackoverflow.com/a/57489435).

**Comment by joachim-quis** [comment]
@agent515 This field is part of the API, but as far as I know it's usually empty, so this is unfortunately not available. (This is why I created the app [Quis](quis.co) 🙂)
