### ISSUE TITLE
Null Phone number problem

### ISSUE THREAD

**Issue by iSaqibShafique** [QuisApp/flutter_contacts#132]
Hi, I am using this package, I've tried with iOS Simulator and also on the real iPhone device but when I get the phone numbers it return null(Empty List).

**Comment by psalmsin1759** [comment]
> Hi, I am using this package, I've tried with iOS Simulator and also on the real iPhone device but when I get the phone numbers it return null(Empty List).

I experienced same

**Comment by raccoondev85** [comment]
pass withProperties: true when you do FlutterContacts.getContacts.

`FlutterContacts.getContacts(withProperties: true, )`

**Comment by tinhnvc-gadget** [comment]
> pass withProperties: true when you do FlutterContacts.getContacts.
> 
> `FlutterContacts.getContacts(withProperties: true, )`

Thanks. It work for me
