### ISSUE TITLE
Quick start code needs to be linted. It's not correct.

### ISSUE THREAD

**Issue by sgehrman** [QuisApp/flutter_contacts#14]
Quick start code needs to be linted. It's not correct.

**Comment by joachim-quis** [comment]
Thanks for flagging! I'll fix it in the next release.

**Comment by joachim-quis** [comment]
Fixed in https://github.com/QuisApp/flutter_contacts/commit/81d72d36eca5675fcc61c97cedee2f01aa6a8b7d and released as part of 1.0.0: https://pub.dev/packages//flutter_contacts#quick-start
