### ISSUE TITLE
Updating alot of contacts withGroups=true in a for loop throws an error. 

### ISSUE THREAD

**Issue by scaleit-lt** [QuisApp/flutter_contacts#140]
android.content.OperationApplicationException: Too many content provider operations between yield points. The maximum number of operations per yield point is 500

Is throws when updating ~120 contacts in for loop. 

This package needs a solution to handle batch updates to avoid this error.

**Comment by joachim-quis** [comment]
Hi @scaleit-lt, the package doesn't yet handle large batch requests. For now, it should be done in the app, but this is a great idea, large batch updates could be handled in the package. Please feel free to submit a PR, happy to review it.
