### ISSUE TITLE
Attempt to present <CNContactPickerViewController> which is already presenting <FlutterViewController>

### ISSUE THREAD

**Issue by aleaforny** [QuisApp/flutter_contacts#141]
With the simple following code:

```
TextButton(
  onPressed: () async {
    final contact = await FlutterContacts.openExternalPick();
  },
  child: Text("Import contact")
),
```

Works perfectly in Android. But on iOS, nothing happens. No error message, nothing, the picker isn't displayed.

After running debugging on Xcode, here the only message displayed when clicking on the text button:
`[Presentation] Attempt to present <CNContactPickerViewController:0x....> on <Runner.SplashViewController: 0x7.....> (from <Runner.SplashViewController: 0x7f......> which is already presenting <FlutterViewController: 0x7f3........>.
`

What is causing this issue?
Thanks a lot

**Comment by joachim-quis** [comment]
With no additional info, it's difficult to help. Please re-open with more details (code, `flutter doctor -v`, etc).

**Comment by aleaforny** [comment]
Finally, I was able to fix it somehow, at least for me and my phones. It could be lead to an official fix it in your package @joachim-quis (but with additional work, of course)

I was experiencing the same issue today, with the latest version (**1.1.9+2**)

Here was my `flutter doctor -v` output :
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [version 10.0.22631.4602], locale fr-FR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
[√] Android Studio (version 2024.1)
[√] Connected device (3 available)
[√] Network resources
```

## ⚡ What was the issue (Steps to reproduce)
1. Define a function to open external picker and read contact

```
void _pickContact() async {
  if (await FlutterContacts.requestPermission(readonly: true)) {
    final contact = await FlutterContacts.openExternalPick();

    if (contact != null) {
      print("Fetched ${contact.displayName} successfully");
    }
  } else {
    print("No permissions");
  }
}
```

2. Call the function directly inside a Widget (can be StatelessWidget, it was in my example) : 
```
@override
Widget build(BuildContext context) {
  return Padding(
    padding: padding ?? EdgeInsets.zero,
    child: TextButton(
      onPressed: () => _pickContact(),
      child: Text("Pick a contact"),
    ),
  );
}
```

3. Test on Android ✅ External picker is displayed upon button's click, and we can see the fetched display name in the console. 

4. Test on iOS ❌ Nothing happens, no external picker is displayed to the user, and no logs are displayed in the Flutter console.

5. It seems that the code doesn't go past `final contact = await FlutterContacts.openExternalPick();`

## ⚡ Further debugging
I was required to debug within Xcode to understand what could happen. The only log entry that appears during the experience is the following :  

`[Presentation] Attempt to present <CNContactPickerViewController:0x....> on <Runner.SplashViewController: 0x7.....> (from <Runner.SplashViewController: 0x7f......> which is already presenting <FlutterViewController: 0x7f3........>. `

Please note that my app was initially built with Flutter 1.0 version, perhaps there are some "old" snippets or whatnot. 

I understood that it probably has something to do with `self.rootViewController`, within the file `SwiftFlutterContactsPlugin.swift`. 


## ⚡ Quick (probably ugly) fix
In my case, I attempt to fetch the parent controller, with a function I defined just before the dispatch : 
```
func getTopViewController(_ rootViewController: UIViewController?) -> UIViewController? {
    if let presented = rootViewController?.presentedViewController {
        return getTopViewController(presented)
    }
    if let navigationController = rootViewController as? UINavigationController {
        return getTopViewController(navigationController.visibleViewController)
    }
    if let tabBarController = rootViewController as? UITabBarController {
        return getTopViewController(tabBarController.selectedViewController)
    }
    return rootViewController
}
```

Then, I can call it before calling `CNContactPickerViewController()` : 

```
guard let topController = getTopViewController(self.rootViewController)
```

And I simply have to replace this line : 
`self.rootViewController.present(contactPicker, animated: true, completion: nil)`
with 
`topController.present(contactPicker, animated: true, completion: nil)`

After that, it works like a charm on iOS ✅ 
(and still Android, of course)


## ⚡ References
You can see the full code here from my fork : https://github.com/aleaforny/flutter_contacts/commit/ccaa3c77813606290a029ccdd6d86e5d66a16300#diff-408b6c212c4e50a2f259f7fcd1df546e1d8d5244bdc91138eb9e4329dce34aa4R656

I've just added checks (such as checking if there aren't already a controller, ie. the initial error I was getting lol) and `FlutterError()` returns, that would gladly help anyone who needs to understand what happens (it can be difficult to have no behavior at all during debugging 🫠 )

Again, would love to see an official update fixing it properly, and surely better than I did.
