### ISSUE TITLE
App Crash when I accept allow button on the permission request message

### ISSUE THREAD

**Issue by gogommd** [QuisApp/flutter_contacts#146]
Code for requestPermission
```
@override
  void initState() {
    super.initState();
    FlutterContacts.requestPermission();
  }
```

Error Output
E/AndroidRuntime( 6871): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.elderly_app/com.example.elderly_app.MainActivity}: java.lang.NullPointerException

**Comment by jerrypaulsam** [comment]
Same issue. Have you resolved it?
