### ISSUE TITLE
Saving multiple number with labels

### ISSUE THREAD

**Issue by nergal79** [QuisApp/flutter_contacts#148]
Thanks for creating this amazing package. 

I m trying to save multiple phone number with different labels . But it only shows first one in form when using `openExternalInsert` with pre-populated data.

> _addContact() async {
     await FlutterContacts.openExternalInsert(
      Contact(
        name: Name(first: 'John', last: 'Doe'),
        phones: [
          Phone('+1 555-123-4567', label: PhoneLabel.mobile),
          Phone('+1 555-123-999', label: PhoneLabel.home),
          Phone('+1 555-123-877', label: PhoneLabel.faxHome)
        ],
        emails: [Email('john.doe@gmail.com')],
        addresses: [Address('123 Main St')],
        websites: [Website('https://flutter.dev')],
        organizations: [Organization(company: 'Flutter', title: 'Developer')],
      ),
    );
  }

I m using the code above .. Right now I am  only testing  this on android .  Is this a library bug or something wrong with my implementation ? 
Any help would be appreciated here. Thx

**Comment by Danjo25** [comment]
I've got the same issue. Did it work in previous versions?

**Comment by nergal79** [comment]
@Danjo25  I did not tried any previous versions.. but its does says that's how it should work in documentation but its not.

**Comment by nergal79** [comment]
I ended up creating my own method channel .. Do not need this library for now .. Closing the issue
