### ISSUE TITLE
openExternalInsert causing SecurityException

### ISSUE THREAD

**Issue by nergal79** [QuisApp/flutter_contacts#150]
AFAIK Opening external intent does not need any permission . When I m trying to add anew contact i'm getting `SecurityException`.
https://developer.android.com/training/contacts-provider/modify-data

    `static insertContact() {

    Contact newContact = Contact(
        displayName: "John",
        name: Name(first: "John"),
        phones: [Phone("+878778788", label: PhoneLabel.mobile)]);
   
        FlutterContacts.openExternalInsert(newContact);
     }`

`java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/data from pid=17024, uid=11474 requires android.permission.READ_CONTACTS, or grantUriPermission()`

Is there something wrong with my implementation ?

**Comment by joachim-quis** [comment]
This is probably the same issue as https://github.com/QuisApp/flutter_contacts/issues/156

It will be included in the next release.
