### ISSUE TITLE
everything is null except displayName

### ISSUE THREAD

**Issue by bawantha** [QuisApp/flutter_contacts#154]
[Contact(id=196D2FA4-04CB-43F7-9FA4-034EFAE7BE5E, displayName=xxxx, thumbnail=null, photo=null, isStarred=false, name=Name(first=, last=, middle=, prefix=, suffix=, nickname=, firstPhonetic=, lastPhonetic=, middlePhonetic=), phones=[], emails=[], addresses=[], organizations=[], websites=[], socialMedias=[], events=[], notes=[], accounts=[], groups=[]), Contact(id=6378D51E-0B02-40DF-9617-FFC4DB88FC67, displayName=xxxx, thumbnail=null, photo=null, isStarred=false, name=Name(first=, last=, middle=, prefix=, suffix=, nickname=, firstPhonetic=, lastPhonetic=, middlePhonetic=), phones=[], emails=[], addresses=[], organizations=[], websites=[], socialMedias=[], events=[], notes=[], accounts=[], groups=[]), Contact(id=DED772D7-C34B-41A1-B147-74F6FA71297E, displayName=xxxx, thumbnail=null, photo=null, isStarred=false, name=Name(first=, last=, middle=, prefix=, suffix=, nickname=, firstPhonetic=, lastPhonetic=, middlePhonetic=), phones=[], emails=[], addresses=[], organizations=[], websites=[], socialMedias=[], events=[], notes=[], accounts=[], groups=[]), Contact(id=71D1269C-08EE-4202-8FC7-8DFAFE41613A, displayName=xxxx, thumbnail=null, photo=null, isStarred=false, name=Name(first=, last=, middle=, prefix=, suffix=, nickname=, firstPhonetic=, lastPhonetic=, middlePhonetic=), phones=[], emails=[], addresses=[], organizations=[], websites=[], socialMedias=[], events=[], notes=[], accounts=[], groups=[]), Contact(id=83304138-BE7E-4355-8C82-E485DB11EEB6:ABPerson, displayName=xxxx, thumbnail=null, photo=null, isStarred=false, name=Name(first=, last=, middle=, prefix=, suffix=, nickname=, firstPhonetic=, lastPhonetic=, middlePhonetic=), phones=[], emails=[], addresses=[], organizations=[], websites=[], socialMedias=[], events=[], notes=[], accounts=[], groups=[]), Contact(id=373F5AE3-0039-4397-B311-F328DE892662:ABPerson, displayName=xxxx, thumbnail=null, photo=null, isStarred=false, name=Name(first=, last=, middle=, prefix=, suffix=, nickname=, firstPhonetic=, lastPhonetic=, middlePhonetic=), phones=[], emails=[], addresses=[], organizations=[], websites=[], socialMedias=[], events=[], notes=[], accounts=[], groups=[]), Contact(id=0E8045C4-094D-4E8F-A728-E46447E9AF04, displayName=xxxx, thumbnail=null, photo=null, isStarred=false, name=Name(first=, last=, middle=, prefix=, suffix=, nickname=, firstPhonetic=, lastPhonetic=, middlePhonetic=), phon

**Comment by bawantha** [comment]
contacts = await FlutterContacts.getContacts(
      withProperties: true, withPhoto: true);

**Comment by Valent1** [comment]
I have opened a similar issue:

https://github.com/QuisApp/flutter_contacts/issues/153

**Comment by bawantha** [comment]
for me  ,it was silly to not to pass ```withProperties = true``` 

> I have opened a similar issue:
> 
> #153
