### ISSUE TITLE
Coudn't get Contacts in new phone, however worked fine in old phone

### ISSUE THREAD

**Issue by AbRehman0346** [QuisApp/flutter_contacts#155]
So I worked according to it's documentation and it works fine in my old phone which had android 10  but doesn't work in my new phone which I bought recently has android 13. I double checked the permissions and everything. It just returns an empty list of contacts. there is no contact in it... However flutter package fast_contacts works fine in both phones. I'm going for fast_contact, but I truely think this package should also work. Thanks.

**Comment by joachim-quis** [comment]
With no additional info, it's difficult to help. Please re-open with more details (code, `flutter doctor -v`, etc).
