### ISSUE TITLE
Latest flutter stable version is breaking with this plugin use. Urgently need fix!

### ISSUE THREAD

**Issue by zuhabul** [QuisApp/flutter_contacts#158]
Execution failed for task ':flutter_contacts:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.

flutter doctor      
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.1)
[✓] VS Code (version 1.79.0-insider)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Hridoy’s iPhone. Ensure the device is unlocked
      and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

**Comment by arabnology** [comment]
Hey, any solution ?

We are waiting this to be fixed ASAP!!

**Comment by arabnology** [comment]
Hello, any news about this ??

**Comment by arabnology** [comment]
Is the package developer still active ?

**Comment by arabnology** [comment]
> Same error here

Unfortunately, the only solution for now is to fallback to Gradle version 7.x.x.

**Comment by joachim-quis** [comment]
@arabnology @rignaneseleo @zuhabul can you try [version 1.1.8](https://pub.dev/packages/flutter_contacts/versions/1.1.8)?

**Comment by himsarevenus** [comment]
still happens in latest version @joachim-quis

**Comment by arabnology** [comment]
> @arabnology @rignaneseleo @zuhabul can you try [version 1.1.8](https://pub.dev/packages/flutter_contacts/versions/1.1.8)?

still happens in latest version :(, please do something

**Comment by himsarevenus** [comment]
I found a workaround @arabnology @joachim-quis 

https://github.com/acoutts/flutter_libphonenumber/issues/70

project(':flutter_contacts').afterEvaluate {
        project(':flutter_contacts').android {
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_17
                targetCompatibility JavaVersion.VERSION_17
            }

            kotlinOptions {
                jvmTarget = '17'
            }
        }
    }

**Comment by zuhabul** [comment]
> I found a workaround @arabnology @joachim-quis
> 
> [acoutts/flutter_libphonenumber#70](https://github.com/acoutts/flutter_libphonenumber/issues/70)
> 
> `project(':flutter_contacts').afterEvaluate { project(':flutter_contacts').android { compileOptions { sourceCompatibility JavaVersion.VERSION_17 targetCompatibility JavaVersion.VERSION_17 } kotlinOptions { jvmTarget = '17' } } }`

This [workaround](https://github.com/QuisApp/flutter_contacts/issues/158#issuecomment-2133860082) solution works but is this a permanent solution for production apps?

**Comment by cyborpaul** [comment]
Any update about it?

**Comment by cyborpaul** [comment]
Try to use this: flutter_contacts_plus: ^1.3.0  with min sdk 23

**Comment by joachim-quis** [comment]
Hi all - thanks for your patience and the recommended solutions.

This should be fixed in [version 1.1.9](https://pub.dev/packages/flutter_contacts/versions/1.1.9). If it is not, please let me know, and reopen this conversation.
