### ISSUE TITLE
open the native contacts app

### ISSUE THREAD

**Issue by andraskende** [QuisApp/flutter_contacts#16]
Could you add an open native contacts function for selected contact ?

Thank you!

**Comment by cedvdb** [comment]
That would be nice indeed.

I don't know enough about ios development to submit a correct PR but this package does it: https://github.com/lukasgit/flutter_contacts

**Comment by joachim-quis** [comment]
Hi @andraskende @cedvdb ! Added in new [version 1.1.0](https://pub.dev/packages/flutter_contacts/versions/1.1.0) with `openExternalView`, `openExternalEdit`, `openExternalPick` and `openExternalInsert`. Let me know if that doesn't work for you.

**Comment by andraskende** [comment]
tried openExternalEdit on android phone worked perfectly,  thank you !

**Comment by cedvdb** [comment]
I'm not sure if the problem is from that new change or not but I've an error:

```
e: D:\Programs\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_contacts-1.1.0\android\src\main\kotlin\co\quis\flutter_contacts\FlutterContacts.kt: (41, 7): Redeclaration: FlutterContacts
e: D:\Programs\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_contacts-1.1.0\android\src\main\kotlin\co\quis\flutter_contacts\FlutterContactsPlugin.kt: (27, 14): Redeclaration: FlutterContactsPlugin
```
