### ISSUE TITLE
Need Guidance on Using Intents Instead of READ_CONTACTS and WRITE_CONTACTS

### ISSUE THREAD

**Issue by ZhiaDev** [QuisApp/flutter_contacts#164]
Hello,

First of all, thank you for the wonderful package you made. The package is very practical and straightforward, but I have encountered an issue.

In my application, I use `newContact.insert();` and `FlutterContacts.openExternalPick();` methods. I have granted 
`READ_CONTACTS` and `WRITE_CONTACTS` permissions in the application.

However, when I wanted to publish my application in the market, they rejected my request, stating that `READ_CONTACTS` and `WRITE_CONTACTS` permissions are considered sensitive. They suggested using `intents` instead.

Could you please guide me on how to handle this? Can this be done with this package, or should I consider using another package? Any help or advice would be greatly appreciated.

Thank you!

**Comment by ZhiaDev** [comment]
please help...

**Comment by arabnology** [comment]
Thats weried!

> please help...

That's weird! I'm already using this package in my project and have already published the app in the stores. Please make sure to clearly show the user why you need contacts permissions.

**Comment by ZhiaDev** [comment]
Hi Mahmoud
I live in your neighborhood in Iran

There are two famous Android stores here, each of which has 40 million users, named Myket and CafeBazaar
My application was correctly published on Myket but not on CafeBazaar, even considering that I explained how the user is supposed to use these features.

They said you should use intents instead of direct access, probably part of their rules

Now, I've been busy all day how to do this through native intents and FlutterChannel, but I haven't succeeded yet.

**Comment by joachim-quis** [comment]
Hi @ZhiaDev - you definitely need the WRITE_CONTACTS permission to do `newContact.insert()`. Contact permissions are indeed considered sensitive by the App Store and the Play store, and you might need to provide justifications as to why you need that permission. They should give you the exact steps to follow in the email rejection your app.
