### ISSUE TITLE
Possible Bug: When Importing Contacts With Phone Number - No Phone Numbers Appear (On Emulated Device)

### ISSUE THREAD

**Issue by TomerPacific** [QuisApp/flutter_contacts#166]
I am using flutter_contacts version **1.1.7+1** to handle importing contacts in my application.

When testing things out, I created a contact on an emulated device and have added two phone numbers to it.

![contact1](https://github.com/QuisApp/flutter_contacts/assets/23402988/8c538752-6730-49ab-951b-3d1bd3c18bbd)

Then, when importing the contact, I see that the phones attribute under the Contact object is empty.

![contact2](https://github.com/QuisApp/flutter_contacts/assets/23402988/237d10a9-bbdf-4ca3-81be-58f9129c2012)

What could be the cause of  this?

You can also see that the **isStarred** attribute is marked as true, even though that is not true for the contact.

The emulated device I am using is a Pixel 4 with API 29

**Comment by joachim-quis** [comment]
Hi @TomerPacific - can you post the code you used?

**Comment by TomerPacific** [comment]
@joachim-quis -
I am getting contacts using this:

`await FlutterContacts.getContacts();`

and then I am iterating over the List<Contact> that it returns like this:

```
for (Contact contact in users) {
      DateTime? chosenBirthDate = await showDatePicker(context: context,
          initialDate: DateTime(1970, 1, 1),
          firstDate: DateTime(1970, 1, 1),
          lastDate: DateTime.now(),
          initialEntryMode: DatePickerEntryMode.input,
          helpText: "Choose birth date for ${contact.displayName}",
          fieldLabelText: "${contact.displayName}'s birth date"
      );

      if (chosenBirthDate != null) {
        UserBirthday userBirthday = new UserBirthday(contact.displayName,
            chosenBirthDate,
            true,
            contact.phones.isNotEmpty ? contact.phones.first.number : "");
      }
    }
```

**Comment by TomerPacific** [comment]
@joachim-quis - any update here?

**Comment by AbhishekSingh-958** [comment]
@joachim-quis Not even on the real device. "phone" field list is empty.

**Comment by TomerPacific** [comment]
@AbhishekSingh-958 - You are correct. This should be documented more clearly.
