### ISSUE TITLE
Not working on iOS 16

### ISSUE THREAD

**Issue by bcatalfo** [QuisApp/flutter_contacts#167]
When I try to run this on a simulator with iOS 16 I get

dyld[53225]: Symbol not found: _swift_getTypeByMangledNameInContext2
  Referenced from: <3FD016D6-1934-3C43-9C67-DFEDBBA61BB0> /Users/bcatalfo/Library/Developer/CoreSimulator/Devices/B21723B0-C7A7-4849-8FBB-C0C2EEF07CC2/data/Containers/Bundle/Application/23FD64B3-0636-4759-855A-871BA80F18BB/Runner.app/Frameworks/flutter_contacts.framework/flutter_contacts (built for iOS-sim 17.0 which is newer than running OS)
  Expected in:     <AD904577-C508-32A8-A605-2024B66B6F1B> /Library/Developer/CoreSimulator/Volumes/iOS_20A360/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 16.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib

**Comment by bcatalfo** [comment]
Nevermind! I had an issue with my Podfile 🙄

**Comment by albrewot** [comment]
@bcatalfo  Can i ask which issue you had with the Podfile?i'm experiencing the same problem with this library an iOS 16

**Comment by bcatalfo** [comment]
All I did was change platform :ios, '17.0' to platform :ios, '16.0'
