### ISSUE TITLE
iOS Xcode 12.5 Could not cast value of type NSNull to NSString

### ISSUE THREAD

**Issue by andraskende** [QuisApp/flutter_contacts#19]
Hi,

Just tried to use the iOS simulator today and it errors out after calling:

    final _contacts1 = await FlutterContacts.getContacts();

error message:

    Could not cast value of type 'NSNull' (0x10495cf18) to 'NSString' (0x10495cf78).

this plugin was working fine, so i thinking maybe something with the recently updated Xcode 12.5 ... 

Thank you !

**Comment by MagTuxGit** [comment]
Not XCode but iOS 14.5

**Comment by andraskende** [comment]
thanks @magTuxGit,  just tested and it works fine with iOS 14.4 simulator, errors out with 14.5.

**Comment by MagTuxGit** [comment]
https://github.com/QuisApp/flutter_contacts/pull/18
This PR fixes this iisue.

**Comment by joachim-quis** [comment]
Thank you all for reporting! I merged #18 and included it in [version 1.0.0+1](https://pub.dev/packages/flutter_contacts/versions/1.0.0+1), let me know if you're still seeing the issue.

**Comment by andraskende** [comment]
its working fine, tested on iOS Simulator 14.4 and 14.5
Thank you !
