### ISSUE TITLE
Android FlutterContacts.requestPermission()) returns false 

### ISSUE THREAD

**Issue by andraskende** [QuisApp/flutter_contacts#20]
Hello,

on Android the FlutterContacts.requestPermission()) started returning false since yesterday changes:

https://github.com/QuisApp/flutter_contacts/blob/master/android/src/main/kotlin/co/quis/flutter_contacts/FlutterContactsPlugin.kt#L75

removing the recently changed grantResults!![1] line seems to fix the issue
grantResults!![1] == PackageManager.PERMISSION_GRANTED

    @override
    void initState() {
      super.initState();
      _askPermissions();
    }

    Future _askPermissions() async {
      if (!await FlutterContacts.requestPermission()) {
        setState(() => _permissionDenied = true);
      }
    }

Thank you !

**Comment by joachim-quis** [comment]
Hi @andraskende, thanks for reporting. It seems to be working for me on emulators and physical device. To help me with debugging:

(1) What is your device and Android version?
(2) Can you confirm [this simple example](https://github.com/QuisApp/flutter_contacts/tree/master/example) also doesn't work?

**Comment by andraskende** [comment]
user error on my part, the example apps works fine

I set only set READ_CONTACTS permission previously as my app only needs to read from contacts...
Since the && fix its also checks for WRITE_CONTACTS for return true, adding the WRITE_CONTACTS permission resolves this issue..

Thanks you !

**Comment by mcfriend99** [comment]
I have WRITE_CONTACTS, but it's not only returning false, it's not even popping up the permissions dialog.
