### ISSUE TITLE
Work without WRITE_CONTACTS permission

### ISSUE THREAD

**Issue by noamraph** [QuisApp/flutter_contacts#25]
Hi,

I only intend to read contacts. I see that in order not to get a "permission denied" result, I have to add both READ_CONTACTS and WRITE_CONTACTS to AndroidManifest.xml.

Is it possible to only request the READ_CONTACTS permission, if I don't intend to modify contacts?

Thanks,
Noam

**Comment by sils** [comment]
I've had the same problem with the builtin permission request feature. However, since I'm already using a different permission requesting plugin for other functionalities, I switched to that which solved the issue for me, as that apparently is fine with requesting read only permission.

**Comment by joachim-quis** [comment]
Hi @noamraph – if you don't intend to modify contacts, you can specify READ_CONTACTS only and stay away from `update`/`delete` methods, and it should work fine. Let me know if it's not the case.

**Comment by joachim-quis** [comment]
Oh, I misunderstood your question, you're referring to `FlutterContacts.requestPermission()`. Indeed at the moment it requests both read and write. I will change that in the next upgrade, so we can request one without the other.

**Comment by joachim-quis** [comment]
Done in [version 1.1.1](https://pub.dev/packages/flutter_contacts/versions/1.1.1).
