### ISSUE TITLE
Calling getContacts returns displayname, phone is null

### ISSUE THREAD

**Issue by sumchans** [QuisApp/flutter_contacts#27]
Hello,

Just noticed this, calling getContacts doesnt return any phone numbers listed on the contact. I see the displaynames returned. When I was printing the contacts this is what I get -
`flutter: Contact(id=D19B3862-865B-4D49-829F-8E8F7658A893:ABPerson, displayName=Home  Surrey, thumbnail=null, photo=null, name=Name(first=, last=, middle=, prefix=, suffix=, nickname=, firstPhonetic=, lastPhonetic=, middlePhonetic=), phones=[], emails=[], addresses=[], organizations=[], websites=[], socialMedias=[], events=[], notes=[], accounts=[])`.

Here is code which is exactly what I copied from here -
`final contacts = await FlutterContacts.getContacts();`

Please advise if I am doing anything wrong here.

**Comment by irajeshh** [comment]
#35 Have the same issue. But don't know why its closed!

**Comment by joachim-quis** [comment]
You simply need to call `await FlutterContacts.getContacts(withProperties: true);`

**Comment by rahmanrezaee** [comment]
the same issue there is any solution??
