### ISSUE TITLE
How to read Android contact Group Membership information?

### ISSUE THREAD

**Issue by TC74** [QuisApp/flutter_contacts#29]
How to read Android contact Group Membership information?

**Comment by joachim-quis** [comment]
Hi @TC74, this is high priority in my list of next features. Added it to the list of feature requests, stay tuned :)

**Comment by TC74** [comment]
BIG thanks! We are planning to use the Contact Group as a meant to filter contacts based on grouping e.g. Primary School, Ex-colleague.

**Comment by joachim-quis** [comment]
Done in [version 1.1.1](https://pub.dev/packages/flutter_contacts/versions/1.1.1).

**Comment by TC74** [comment]
Thanks. I look up your version 1.1.1 but did not see the Contract Group
Membership detail. See
https://developer.android.com/reference/android/provider/Contacts.GroupMembership

**Comment by TC74** [comment]
Sorry, please ignore. Saw it is deprecated.

https://developer.android.com/reference/android/provider/ContactsContract.Groups

**Comment by joachim-quis** [comment]
Correct :) On Android the relevant classes are `ContactsContract.CommonDataKinds.GroupMembership` and `ContactsContract.Groups`.

You can now see the groups by fetching contacts via `FlutterContacts.getContacts(withProperties: true, withGroups: true)` and for example the group name will be in `contact.groups[0].name`.
