### ISSUE TITLE
Saving New Contact with Specified id

### ISSUE THREAD

**Issue by buzzicards** [QuisApp/flutter_contacts#3]
Hello,

Was wondering if its possible to save new contact with my own specified id? 

Also is possible to update existing contact using id? 

Hope to get your help. 

Thanks,

**Comment by joachimvalente** [comment]
No, you can't specify your own ID when creating a new contact. The underlying platform (Android or iOS) handles that for you.

Not sure what you're asking exactly about updating a contact using the ID.

**Comment by buzzicards** [comment]
Thanks,

Was just wondering if i could specify the id with a string i create in my app, so when user needs to update a contact in his list i check for the id then update the correct contact.

**Comment by joachimvalente** [comment]
Unfortunately you don't have control over the ID since it is the ID of the contact in the native database. The best way to do this is to get the `contact.id` first (either after calling `getContact` or `newContact`), and then using that contact ID.

**Comment by joachimvalente** [comment]
Does that answer the question? Otherwise can you clarify what you are trying to do exactly?

**Comment by buzzicards** [comment]
So let say I have 15 contacts in my list of contacts and 10 of them have same name with different phone numbers. 

How do i sort them out ?

  /// Get all fields (phones, emails, photo, job, etc) for a given contact
    Contact contact = await FlutterContacts.getContact(contacts.first.id);

This only gives me the first list on the contact list. Would i be able to loop through the list of contact and then check for instead if url is equal to value then i know this is the contact am looking for then I go ahead and update that contact. 

Not sure if am clear. 

Just trying to find a way  to update contact without overwritten the wrong contact.

Thanks alot for your time

**Comment by joachimvalente** [comment]
If they all have the same name, you need something else to know which one is the right one. Let's say you want to update the ones that have no phone numbers:

```dart
var contacts = await FlutterContacts
    .getFullContacts()
    .where((c) => c.displayName == 'John Smith' && c.phones.isEmpty)
    .toList();
for (var c in contacts) {
  c.phones.add(Phone('12 34 56'));
  await FlutterContacts.updateContact(c);
}
```

Or, say you want to update just the ones that were created within your app.

```dart
// Create contact
final c = await Flutter contacts.newContact()
  ..name.first = 'John'
  ..name.last = 'Smith';
final id = c.id;

// Save the ID somewhere, maybe in a Sqlite3 database or a file or just SharedPreferences
final prefs = await SharedPreferences.getInstance();
final ids = (prefs.getString('ids') ?? '').split(',');
prefs.setString('ids', (ids + [id]).join(','));

// Later, update every contact created within the app
final prefs = await SharedPreferences.getInstance();
final ids = (prefs.getString('ids') ?? '').split(',');
var contacts = await FlutterContacts
    .getFullContacts()
    .where((c) => ids.contains(c.id))
    .toList();
for (var c in contacts) {
  c.phones.add(Phone('12 34 56'));
  await FlutterContacts.updateContact(c);
}
```

Does that make sense?

**Comment by buzzicards** [comment]
Makes sense... Just make quick update and noticed this error

The method 'where' isn't defined for the type 'Future'.
Try correcting the name to the name of an existing method, or defining a method named 'where'.

I will look into it more when i get home. 

Thanks for your support.

**Comment by joachimvalente** [comment]
Sorry I typed that on my phone and forgot the parentheses.

```dart
var contacts = (await FlutterContacts
    .getFullContacts())
    .where((c) => ids.contains(c.id))
    .toList();
```

**Comment by buzzicards** [comment]
@joachimvalente  Thanks for the feedback. Got it working
