### ISSUE TITLE
Feature request: Add parameters to openExternalInsert()

### ISSUE THREAD

**Issue by jj-gh** [QuisApp/flutter_contacts#30]
The main thing I really want is for the user to have the option whether to save the contact to device or cloud storage.  I saw that openExternalInsert() gives the option to do that, but there's no way to pre-populate it (that I'm aware of). I tried a solution using insert() first, then openExternalEdit(contact.id), but apparently the storage location for existing contacts can't be changed.  So I was wondering if it was possible to pre-populate the fields of the native contact creator via passing parameters to openExternalInsert(). But if there's already a way to do this, any guidance would be appreciated.

Edit: Preferably, the parameter would just be of type Contact

**Comment by joachim-quis** [comment]
Hi! I'm not sure what you're requesting exactly. Currently `flutter_contacts` only deals with the local (on device) contact database, and any cloud storage or sync happens outside of it. But maybe I misunderstood what you're asking?

**Comment by jj-gh** [comment]
I know it only deals with local contact database, but flutter_contacts has a method called openExternalInsert() which, as the name suggests, opens the native (OS specific) interface to add a contact. And in that interface, there's an option to choose whether to save the contact locally, or in whatever online account you have setup in the device (Google, etc.). The only problem is, you have to input the contact information manually. If I already have a Contact object (from the flutter_contacts library), I would like to be able to pass it to the openExternalInsert() so that the native interface form will be populated with it. I'm asking if that would be possible to implement. I appologize if it's still confusing, I'm really trying my best to explain it as clear as I can.
