### ISSUE TITLE
Photo encoding is broken

### ISSUE THREAD

**Issue by cardeo-ewan** [QuisApp/flutter_contacts#34]
The easiest way to see this is to do the following
```dart
Contact contact
avatar(contact) // DIsplays the photograph
String vCard = contact.toVCard();
contact = Contact.fromVCard(); // Silently fails with a FormatException on line 114 of vcard.dart
avatar(contact) // doesn't display a photo
```
The problem is in lines 327 to 340 of `contact.dart`.  The padding isn't being done correctly.  A simple way of fixing this is to get rid of all the individual line stuff and replace it with
```dart
  if (withPhoto && photoOrThumbnail != null) {
      final encoding = vCardEncode(base64.encode(photoOrThumbnail!));

      final prefix =
          v4 ? 'PHOTO:data:image/jpeg;base64,' : 'PHOTO;ENCODING=b;TYPE=JPEG:';
      lines.add(prefix + encoding);
    }
```

You do get a massively long line but all the clients of vCards I have tried seem to work.

**Comment by joachim-quis** [comment]
Thanks @cardeo-ewan for reporting! Incorporated your fix to [version 1.1.2](https://pub.dev/packages/flutter_contacts/versions/1.1.2).
