### ISSUE TITLE
Issue in Contact.fromMap()

### ISSUE THREAD

**Issue by jsteinberg7** [QuisApp/flutter_contacts#36]
E/flutter ( 5209): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Item' is not a subtype of type 'Map<dynamic, dynamic>'
E/flutter ( 5209): #0      new Contact.fromMap.<anonymous closure>
package:contacts_service/contacts_service.dart:237
E/flutter ( 5209): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter ( 5209): #2      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter ( 5209): #3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter ( 5209): #4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter ( 5209): #5      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter ( 5209): #6      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter ( 5209): #7      new Contact.fromMap
package:contacts_service/contacts_service.dart:237

**Comment by joachim-quis** [comment]
Looks like it's from a different package :)
