### ISSUE TITLE
how to get favorite/starred contacts

### ISSUE THREAD

**Issue by kweon-hak** [QuisApp/flutter_contacts#37]
Hello 
How can I get the favorite / starred contacts?

**Comment by joachim-quis** [comment]
Hi @kweon-hak! Just made it possible in [version 1.1.2](https://pub.dev/packages/flutter_contacts/versions/1.1.2), let me know if it works for you! Note that it's apparently not possible on iOS since favorites are stored on the default contact app and not in the contacts database.

**Comment by kweon-hak** [comment]
It works well !
Thanks,
