### ISSUE TITLE
How comes the contact.phone number list of contact empty ?

### ISSUE THREAD

**Issue by Iampato** [QuisApp/flutter_contacts#4]
`List<Contact> contacts = await FlutterContacts.getContacts();`
All of my contacts contact.phone(list) are all empty

**Comment by joachimvalente** [comment]
By default `getContacts()` only fetches IDs and display names. To fetch everything including photos and phone numbers, use `getFullContacts()` instead.

**Comment by Iampato** [comment]
that's expensive ... why not make one query to do all that or just a basic displayname and phone number

**Comment by Iampato** [comment]
Thanks, it works
