### ISSUE TITLE
Updating contact is destroying my contact

### ISSUE THREAD

**Issue by developer01-dufour-one** [QuisApp/flutter_contacts#40]
Android 11, Redmi Note 8 Pro

When updating my contact with an updated note (see code below), my contact gets brokened up:
-  all the information is erased from the contact (name gone, email gone, all inner info gone)
- the picture or thumbnail remains
- the contact is not deleted, only empty. 

From trying with several contacts, it looks like this happens to contacts that have a thumbnail but no image. When both are there, i did not see the problem happening. 

Here is the relevant code used below, let me know if you need more. 

```
    Contact? contact= await FlutterContacts.getContact(friend.contactImportId,
        withPhoto: true, withThumbnail: true, withProperties: true,withAccounts: true);
    if(loadedContact == null){
      print("loadedContact == null");
      return;}
    print("ContactID = ${friend.contactImportId}");
```

................

```
    List<Note> notes = contact.notes;
    Note note = notes[0];
    note.note += toStoreString;
    await contact.update();
```

**Comment by joachim-quis** [comment]
I am trying this exact setup with the `example_full` app in the package, and I can't reproduce it. Can you try again with that example app, and reopen the ticket if it still doesn't work?
