### ISSUE TITLE
Couldn't read row 830, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.

### ISSUE THREAD

**Issue by GalacticTitan** [QuisApp/flutter_contacts#44]
**Non-fatal Exception: java.lang.IllegalStateException**

Couldn't read row 830, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.

android.database.CursorWindow.nativeGetString (CursorWindow.java)
android.database.CursorWrapper.getString (CursorWrapper.java:141)
co.quis.flutter_contacts.FlutterContacts$Companion.select$getString (FlutterContacts.java:190)
co.quis.flutter_contacts.FlutterContacts$Companion.select (FlutterContacts.java:196)
co.quis.flutter_contacts.FlutterContacts$Companion.select$default (FlutterContacts.java:55)
co.quis.flutter_contacts.FlutterContactsPlugin$onMethodCall$2.invokeSuspend (FlutterContactsPlugin.java:213)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:106)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.java:571)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.java:750)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.java:678)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.java:665)

Getting this sometimes.

**Comment by joachim-quis** [comment]
Thanks @GalacticTitan for reporting. The stack trace is not sufficient to debug anything. Please reopen this ticket if it happens again or if you're able to give some approximative steps to reproduce the issue.
