### ISSUE TITLE
openExternalPick function has returns contact without rawid

### ISSUE THREAD

**Issue by abhay-s-rawat** [QuisApp/flutter_contacts#45]
I updated openExternalPick function so that the returned contact can be updated . Previously it was throwing error because getContact has withAccounts to false by default.
```
Previously
  static Future<Contact?> openExternalPick() async {
    final id = await _channel.invokeMethod('openExternalPick');
    return id == null ? null : getContact(id);
  }
```
```
After updating
  static Future<Contact?> openExternalPick() async {
    final id = await _channel.invokeMethod('openExternalPick');
    return id == null ? null : getContact(id, withAccounts: true);
  }
```
Forked and made changes in below repo
https://github.com/abhay-s-rawat/flutter_contacts

**Comment by joachim-quis** [comment]
Thanks @abhay-s-rawat for your suggestion. The returned contact only contains ID and display name, since that's the fastest. If anything else is needed, such as raw ID or phone numbers or photos, please call `getContact()` with the returned contact's ID.
