### ISSUE TITLE
Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range

### ISSUE THREAD

**Issue by AlexF1983** [QuisApp/flutter_contacts#46]
with Version 1.1.2

```
  Future<void> insertContact() async {
    if (!await FlutterContacts.requestPermission(readonly: true)) {
      setState(() => _permissionDenied = true);
    } else {
      final contacts = await FlutterContacts.getContacts();
      setState(() => _contacts = contacts);

      for (var i = 0; i <= _contacts!.length; i++) {
        final fullContact = await FlutterContacts.getContact(_contacts![i].id);

        if (fullContact!.phones.first.normalizedNumber.isNotEmpty) {
          savecontact(userid, _contacts![i].displayName, fullContact.phones.first.normalizedNumber);
        }
      }
    }
  }
```

E/flutter (13307): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..69: 70
E/flutter (13307): #0      List.[] (dart:core-patch/growable_array.dart:254:60)
E/flutter (13307): #1      _MyHomePageState.insertContact (package:mypack/matapp.dart:159:48)
E/flutter (13307): <asynchronous suspension>

Is this a serious problem/error? Is there a solution? Thank you.

**Comment by joachim-quis** [comment]
@AlexF1983 this is probably because `fullContact.phones` is empty for some of your contacts, so `fullContact.phones.first` raises an exception.
