### ISSUE TITLE
new contact add group

### ISSUE THREAD

**Issue by softdeveloper88** [QuisApp/flutter_contacts#47]
can't insert groups list with new contact number

**Comment by joachim-quis** [comment]
Hi @softdeveloper88! Can you clarify the question? Can you share any code you tried?

**Comment by softdeveloper88** [comment]
when I add new contact number so I can insert list of email and list of contact but list group which I want also add this number to the required group .
 ```
final newContact = Contact()
                          ..photo = profileImage
                          ..name.first = firstNameController!.text
                          ..name.last = lastNameController!.text
                          ..phones = _contactsList
                          ..emails = _emailList
                          ..groups = selectGroup;     // group list not added with new  contact adding time 
                        await newContact.insert();
```

**Comment by joachim-quis** [comment]
@softdeveloper88 Groups are currently read-only. Writing groups is coming soon.

**Comment by tkleijkers-innervate** [comment]
@joachim-quis Do you have any timeline for this functionality (adding groups)?

**Comment by felixkriechbaum** [comment]
On iOS it is not possible to add Contact to Group, on android it is working as intend but on iOS not.
I create the group, and add the contact but the contact is not added to the group.
