### ISSUE TITLE
can not read person with group

### ISSUE THREAD

**Issue by yeahse** [QuisApp/flutter_contacts#50]
if someone has a group then can\`t read him (it doesn\`t read him at first time, if he has a group)

final contacts = await FlutterContacts.getContacts(withGroups: true);

not working at all

**Comment by joachim-quis** [comment]
Sorry I can't help without more details. Feel free to re-open with more details regarding what you'd expect and what you're getting instead.

**Comment by yassinsameh** [comment]
Issue still persisting in Android 13, flutter_contacts: ^1.1.6. 

Steps to replicate: 
1) Create a contact with no group
2)```
await FlutterContacts.getContacts(
        withProperties: true,
        withGroups: true,
        deduplicateProperties: true,
      ); 
```
Contact will be fetched correctly
 3) Add that contact to a group (Besides the emergency group as that's the only one that works) 
 4) Use same Query in 2), contact is not returned
 
 @joachim-quis @yeahse
