### ISSUE TITLE
The plugin not get all contacts

### ISSUE THREAD

**Issue by Ghoust-Dev** [QuisApp/flutter_contacts#52]
i used this package and not retreive all contacts only 267 contacts and stoped but when i used other package like contacts_service retreive all contacts

**Comment by joachim-quis** [comment]
Are you on Android or iOS? Can you explain what you'd expect and what you're getting instead?
Note that by default only "visible" contacts are returned (see this [stackoverflow article](https://stackoverflow.com/questions/28665587/what-does-contactscontract-contacts-in-visible-group-mean-in-android)). If you want to include them, add `FlutterContacts.config. includeNonVisibleOnAndroid = true;` before calling FlutterContacts.

**Comment by joachim-quis** [comment]
Closing as unreproducible.
