### ISSUE TITLE
Get contact using phone number

### ISSUE THREAD

**Issue by ranahyder87** [QuisApp/flutter_contacts#57]
.getContact() takes id of the contact. But what if I have a phone number and want to get its Contact object?

**Comment by yusufmustu** [comment]
@ranahyder87 you can use this
      final contacts = await FlutterContacts.getContacts(withProperties: true, withPhoto: true);
      final option_1 = contacts.firstWhere((c) => c.phones.any((a) => a.normalizedNumber == '+90544391XXXX'));
      final option_2 = contacts.where((c) => c.phones.any((a) => a.normalizedNumber.contains('1234'))).toList();

**Comment by joachim-quis** [comment]
Correct, FlutterContacts doesn't support to get a contact by its phone number directly. The only option currently is to fetch them all like @yusufmustu suggested.

**Comment by AbodiSadiqGitHub** [comment]
Thanks @yusufmustu

It works me.
