### ISSUE TITLE
json_serializable dev dependency is redundant

### ISSUE THREAD

**Issue by ycherniavskyi** [QuisApp/flutter_contacts#6]
It seems that `json_serializable` dev dependency, which points to add in the first step of [installation](https://github.com/QuisApp/flutter_contacts#installation), is redundant.

I just didn't add it and everything compiled without any issue on Android and iOS.

**Comment by joachimvalente** [comment]
Thanks a lot for flagging! I'm about to release a new version that doesn't depend on `json_serializable` / `build_runner` at all anyway, and I'll update the docs.

**Comment by ycherniavskyi** [comment]
It sounds great.

But I am curious, do you have some issue with `json_serializable` so that you decided to get rid of it?

**Comment by joachimvalente** [comment]
I initially used it to avoid boilerplate, but there are a lot of things it doesn't do, like `toString()`, `operator==`, `hashCode`, and types `Uint8List` and a few other things for which you need custom logic anyway.
