### ISSUE TITLE
get contact doesn't work

### ISSUE THREAD

**Issue by kayson3** [QuisApp/flutter_contacts#61]
contacts = await FlutterContacts.getContacts(
      withProperties: true, withPhoto: true);

This ...

It works the first time I run the app but doesn't anymore

**Comment by A7MeDG0L0L** [comment]
Same.

**Comment by kayson3** [comment]
It actually works it just takes time to fetch the contacts

**Comment by kayson3** [comment]
It actually works it just takes time to fetch the contacts

**Comment by joachim-quis** [comment]
Closing, feel free to reopen if it happens again.
