### ISSUE TITLE
[Feature] Add new contact passing some info to the native screen

### ISSUE THREAD

**Issue by marcodecarolisidt** [QuisApp/flutter_contacts#66]
Would it be possible to open the Add native screen with **openExternalInsert** and pass some information like names and phone numbers, so the user doesn’t have to type them?

**Comment by jjochen** [comment]
Ideally you could pass a `Contact` object to the `openExternalInsert` method.

**Comment by jjochen** [comment]
Any news here?

**Comment by marcodecarolisidt** [comment]
Waiting as well :)

**Comment by anna-noell** [comment]
Any news on this? ty

**Comment by anoop-dtrans** [comment]
The feature #109  has been added `openExtenalInsert([Contact?])` as of version `1.1.7`.
