### ISSUE TITLE
Kotlin Version

### ISSUE THREAD

**Issue by Crucialjun** [QuisApp/flutter_contacts#69]
Hitting this error after updating gradle

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_contacts' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0

**Comment by westito** [comment]
Any updates? It is very urgent

**Comment by joachimvalente** [comment]
Sorry for the delay. Should be fixed in [version 1.1.6](https://pub.dev/packages/flutter_contacts/versions/1.1.6)
