### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by matejthetree** [QuisApp/flutter_contacts#7]
Hello,

love your package.

Do you have any plants to migrate to null safety?

**Comment by joachimvalente** [comment]
Thank you :)

I do! I'll try to do it by next week.

**Comment by joachimvalente** [comment]
Should be done with version 0.3+

Let me know if that works for you!

**Comment by joachimvalente** [comment]
Just on time for Dart 2.12 stable release :D

**Comment by matejthetree** [comment]
nice. thank you.
