### ISSUE TITLE
openExternalInsert on IOS stacks on Edit, impossible to return back to app

### ISSUE THREAD

**Issue by fullflash** [QuisApp/flutter_contacts#70]
after creating contact done button display a contact card with Cancel And Edit action buttons
should be Done to return back to flutter but the Cancel button also does no action it just stack on Native Contact Editor.

**Comment by ewankirk** [comment]
I have the same problem on iOS 16.0 and 15.4.  Seems to work perfectly on Android though.

**Comment by ewankirk** [comment]
Sorry, I should have said that this is openExternalEdit()

**Comment by ewankirk** [comment]
A bit more information.  
If you call openExternalEdit() and immediately hit back, you return to the app.
If you call openExternalEdit() and then hit Edit and then hit cancel, you return to the display screen and then the back button stops working (even if you haven't edited anything).  I suspect what is happening is that openExternalEdit() is actually opening the external *view* by mistake and then when you go to edit, it gets confused with the route.

**Comment by joachim-quis** [comment]
Copying screenshots from duplicate bug:

> ![Screenshot 2022-10-26 at 10 32 12 AM](https://user-images.githubusercontent.com/94591962/197939781-c657fceb-a43f-4feb-95a7-61d9536ed2db.png)
> 
> ![Screenshot 2022-10-26 at 10 31 59 AM](https://user-images.githubusercontent.com/94591962/197939794-92b71107-23f4-4429-ad9f-016654838943.png)
> 
> The back button after clicking edit is showing no response

**Comment by yassinsameh** [comment]
Issue still persists on flutter_contacts: ^1.1.5+1, running Ios 16.1.1.

**Comment by starshipcoder** [comment]
I have donen a PR : #104

**Comment by Shahidbangash** [comment]
> I have donen a PR : #104

I tested your Pr Locally and it works. Thanks for the fix.

**Comment by joachim-quis** [comment]
Should be fixed in version [1.1.7](https://pub.dev/packages/flutter_contacts/versions/1.1.7)
