### ISSUE TITLE
Open contact preview

### ISSUE THREAD

**Issue by simkosal** [QuisApp/flutter_contacts#73]
I have VCARD like this
`"BEGIN:VCARD
VERSION:3.0
N:Messi;Lionel;;;
TEL;TYPE=cell,msg:9090808010
EMAIL;TYPE=internet:messi@gmail.com
ADR;TYPE=home:;;1234;Paris;City new;;France
ORG:ParisClub@gmail.com
URL:www.messi.com
END:VCARD"`

currently, I can only load the contact detail base on the existing contact (By contact Id)

My purpose is: 
1. load VCARD data on a preview contact
2.  user can save to contact or later

Here is what I plan to do
https://i.imgur.com/ObC6vRY.jpg

Thank you!

**Comment by joachim-quis** [comment]
Hi @simkosal. You can just create a Contact object from it, without saving it to the database. Your app can display it temporarily in a custom UI.
