### ISSUE TITLE
on calling openExternalEdit in IOS After edit unable to return back to app 

### ISSUE THREAD

**Issue by Adithyan2295** [QuisApp/flutter_contacts#74]
![Screenshot 2022-10-26 at 10 32 12 AM](https://user-images.githubusercontent.com/94591962/197939781-c657fceb-a43f-4feb-95a7-61d9536ed2db.png)

![Screenshot 2022-10-26 at 10 31 59 AM](https://user-images.githubusercontent.com/94591962/197939794-92b71107-23f4-4429-ad9f-016654838943.png)

The back button after clicking edit is showing no response

**Comment by tanukijs** [comment]
+1

**Comment by joachim-quis** [comment]
Thanks @Adithyan2295 for reporting. Closing as duplicate of https://github.com/QuisApp/flutter_contacts/issues/70
