### ISSUE TITLE
Support storing In Hive,ObjectBox.

### ISSUE THREAD

**Issue by yassinsameh** [QuisApp/flutter_contacts#76]
Hi, currently it's not possible to store a Contact object to hive as that object must be immutable and have certain annotations the run a build_runner. Is there a way i'm not aware of that this can be achieved? Besides forking the repo and editing the Contact class? If there is a way that makes sense to support this i would gladly work on it and make a pull request.

**Comment by yassinsameh** [comment]
Workaround found, storing the contact as Json using the toJson() method and fetching after using the fromJson() method.

**Comment by akamanocha** [comment]
Hi @yassinsameh can you please help with some sample code .Thanks.

**Comment by yassinsameh** [comment]
Hi, an example would be to have your class 
`StoredContact{
final Map<String,dynamic> contact
}
`
Then you can store/get your Contact using the toJson() and fromJson() methods.
