### ISSUE TITLE
Update kotlin 

### ISSUE THREAD

**Issue by mouryaavadhesh** [QuisApp/flutter_contacts#89]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_contacts' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0

You need to update the latest kotlin version in your code

**Comment by Zelfapp** [comment]
Same

![image](https://user-images.githubusercontent.com/11559805/208225436-d18192a3-6fe4-4327-a142-a5e6523c01fc.png)

**Comment by Mohammad-Abureesh** [comment]
same issues , withe me when update to latest kotlin version '17.3'

**Comment by codetinker** [comment]
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. The following dependencies do not satisfy the required version: project ':flutter_contacts' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0
> 
> You need to update the latest kotlin version in your code

Same issues

**Comment by DanLux** [comment]
I am also facing the same issue right now.

**Comment by joachim-quis** [comment]
Thanks for reporting. Will update fix ASAP.

**Comment by joachim-quis** [comment]
See also https://github.com/QuisApp/flutter_contacts/issues/90

**Comment by joachimvalente** [comment]
Duplicate of #69  (now fixed)
