### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by Billy-80** [QuisApp/flutter_contacts#9]
Hello first. Upon running the function below on Android, if the contact has a picture assigned it gets deleted ( seems to be deleted). Same happens when trying to update a contact name. When the function below runs, the address is updated successfully but the pic is not visible on the device native contacts app. I have tested on both an emulator and a real device. The same code works OK for IOS without issues. 

fn1() async{

Contact testContact = await FlutterContacts.getContact('some ID');
Address testAddress = Address('test', customLabel: 'test' , label: AddressLabel.custom);  
testContact.addresses.insert(0, testAddress);
await testContact.update();

}
This is on version ^0.2.2 as I haven’t yet migrated to null safety.

**Comment by joachimvalente** [comment]
Hi, I'll look into this shortly. But in the meantime, you should be able to move to 0.3.3 (or more recent) even if you're not using null-safety in the rest of your project.

**Comment by joachim-quis** [comment]
Hey @Billy-80 I could reproduce the issue. https://github.com/QuisApp/flutter_contacts/commit/a391dbfe80063ef5e01eb1a2e1875bf3bef043cc should fix it, and I'll include in the next version.

**Comment by joachimvalente** [comment]
Just cut a new version 0.3.3+1 with the fix. Thanks for reporting!

Feel free to reopen if needed.
