### ISSUE TITLE
Flutter contact on build appbundle

### ISSUE THREAD

**Issue by Mohammad-Abureesh** [QuisApp/flutter_contacts#90]
current kotlin version 1.4.0 replace to  **ext.kotlin_version = '1.7.10'**

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. 

The following dependencies do not satisfy the required version: project ':flutter_contacts' -> org.jetbrains.kotlin:kotlin-gradle-plugin**:1.4.0**

**Comment by joachim-quis** [comment]
Duplicate of #89
