### ISSUE TITLE
Notes not being fetching even with entitlement

### ISSUE THREAD

**Issue by yassinsameh** [QuisApp/flutter_contacts#94]
I have the contacts notes entitlement, the contacts in general are being fetched when setting `FlutterContacts.config.includeNotesOnIos13AndAbove = true;

However the contact itself is fetched with no Notes even though i added it in the contact.
`

flutter_contacts: 1.1.5+1

**Comment by joachim-quis** [comment]
Hi, thanks for reporting. There is a fix suggested in https://github.com/QuisApp/flutter_contacts/issues/67
I will add the fix in the next version of the plugin.
